Initial version of atom flatpak
endlessm/atom-flatpak pull request #1
Opened 2017-03-08 10:37 UTC by krnowak

https://phabricator.endlessm.com/T14295

2017-03-08 11:05 UTC, lilic requested changes
Will try building and let you know if I find anything else.

2017-03-08 11:05 UTC, LiliC commented on build.sh
> +    ostree  init --mode=archive-z2 --repo=repo
one space too many ;)

2017-03-08 11:05 UTC, LiliC commented on resources/install
> +olddesktop="${appdir}/atom.desktop"
You can just use `rename-desktop-file` in your json manifest file.

> Any desktop file with this name will be renamed to a name based on id during the cleanup phase.

2017-03-08 11:05 UTC, LiliC commented on atom/install
> +    install -D "${icon}" "${prefix}/share/icons/hicolor/${size}x${size}/apps/io.atom.Atom.png"
There is also `rename-icon`, which you can use in your json manifest file:
> Any icon with this name will be renamed to a name based on id during the cleanup phase.

2017-03-08 11:20 UTC, LiliC commented on io.atom.Atom.json
> +                    "type": "patch",
@krnowak I get the following error when building:
```
Downloading https://download.gnome.org/sources/libgnome-keyring/3.12/libgnome-keyring-3.12.0.tar.xz
Failed to download sources: module libgnome-keyring: Can't find file at libgnome-keyring/libgnome-keyring-detect-gcrypt.patch
```
Did you maybe forget to include the patch?

2017-03-08 14:37 UTC, krnowak commented on build.sh
> +    ostree  init --mode=archive-z2 --repo=repo
Haha, copy-pasta FTW.

2017-03-08 14:38 UTC, krnowak commented on atom/install
> +    install -D "${icon}" "${prefix}/share/icons/hicolor/${size}x${size}/apps/io.atom.Atom.png"
Have to check it, but I'm not exactly renaming here. All the icons have the name like `<size>.png`, so `128.png` or `64.png`. But I'll check this `rename-icon` thing, thanks.

2017-03-08 14:39 UTC, krnowak commented on io.atom.Atom.json
> +                    "type": "patch",
Duh, of course I forgot.

2017-03-08 14:42 UTC, krnowak commented on resources/install
> +olddesktop="${appdir}/atom.desktop"
I would use it if I was going to only rename the desktop file, but I'm also patching it to use a different icon name, so I'll keep it like that for now.

2017-03-08 14:43 UTC, krnowak commented on atom/install
> +    install -D "${icon}" "${prefix}/share/icons/hicolor/${size}x${size}/apps/io.atom.Atom.png"
Yeah, that wouldn't work for us here.

2017-03-08 14:45 UTC, krnowak commented on io.atom.Atom.json
> +                    "type": "patch",
Fixed.

2017-03-08 15:43 UTC, krnowak commented
PR updated.

2017-03-08 16:30 UTC, LiliC commented
Seems like this error repeats a lot:
```
Window manager warning: 0x1c00001 (untitled —) appears to be one of the offending windows with a timestamp of 36576935.  Working around...
Window manager warning: last_user_time (36577019) is greater than comparison timestamp (36577017).  This most likely represents a buggy client sending inaccurate timestamps in messages such as _NET_ACTIVE_WINDOW. Trying to work around...
```
Had some problems with running certain packages for example Hydrogen. Not sure if thats a flatpak error or the package error. Attaching screenshot.
<img width="459" alt="screen shot 2017-03-08 at 17 10 33" src="https://cloud.githubusercontent.com/assets/6232346/23712448/3f1e12a8-0423-11e7-8afe-551c5dce2091.png">

One other thing is the init coffee script, css and the config files are empty, usually they come preloaded with comments and examples, not sure that works correctly there. Maybe you can have a look.

Otherwise works OK. 👍

2017-03-08 17:56 UTC, ptomato commented
Do you know about https://github.com/mattdangerw/atom/commit/e54494fb63999174a7195b307dabd82dd7c0659f ?

2017-03-09 01:16 UTC, cosimoc requested changes

2017-03-09 01:16 UTC, cosimoc commented on io.atom.Atom.json
> +        /* Allow access to developer tools */
Remove the comments, otherwise Jenkins will choke on the JSON.

2017-03-09 11:27 UTC, krnowak commented
@ptomato: Yes, I've seen that and I think this is a bit pointless - `./build/script --install=/app` does most of the things we want with fewer lines of code. Also, using flatpak-builder directly makes it easier to integrate with the endless jenkins instance.

2017-03-09 11:27 UTC, krnowak commented on io.atom.Atom.json
> +        /* Allow access to developer tools */
Comments removed.

2017-03-13 18:31 UTC, merged